spring:
  datasource:
    initialization-mode: always
    platform: MYSQL
    continue-on-error: true
    driver-class-name: "com.mysql.jdbc.Driver"
    url: jdbc:mysql://127.0.0.1:3306/k8s_console?useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: Admin@123
    hikari:
      minimum-idle: 30
      maximum-pool-size: 300
      pool-name: hikari
      idle-timeout: 18000
      connection-timeout: 180000
      max-lifetime: 1800000
    # Switch this on to create the schema, insert data on startup
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    showSql: true
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-handlers-package: com.cynricshu.mybatis.typehandler